name: CI - run tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  call-build:
    name: Build and test on Node.js ${{ matrix.node-version }}
    strategy:
      matrix:
        node-version: [18, 20]
      fail-fast: false
      max-parallel: 2
    uses: ./.github/workflows/build.yml
    with:
      node-version: ${{ matrix.node-version }}
      run-tests: true
    secrets:
      token: ${{ secrets.PLATFORM_TOKEN }}
